In [2]:
import pandas as pd
import numpy as np

print('Pandas:', pd.__version__)
print('NumPy:', np.__version__)

Pandas: 3.0.3
NumPy: 2.4.6

In [3]:
# a partir de listas
dados = [['Joaquim', 4, 'Curitiba', 'PR'],
         ['Vanessa', 42, 'Pato Branco', 'PR'],
         ['Alzemiro', 92, 'Espumoso', 'RS'],
         ['Alice', 33, 'São Paulo', 'SP']]

colunas = ['Nome', 'Idade', 'Cidade', 'Estado']

# criando um DataFrame a partir de listas
df = pd.DataFrame(dados, columns=colunas)

print(type(df))
print()
print(df)

<class 'pandas.DataFrame'>

       Nome  Idade       Cidade Estado
0   Joaquim      4     Curitiba     PR
1   Vanessa     42  Pato Branco     PR
2  Alzemiro     92     Espumoso     RS
3     Alice     33    São Paulo     SP

In [5]:
# criando um DataFrame a partir de um dicionário de dados
dic = {'Nome' : ['Joaquim', 'Vanessa', 'Alzemiro', 'Alice'],	
       'Idade' : [4, 42, 92, 33],
       'Cidade' : ['Curitiba', 'Pato Branco', 'Espumoso', 'São Paulo'],
       'Estado' : ['PR', 'PR', 'RS', 'SP']}

print(type(dic))

df = pd.DataFrame(dic)
print(type(df))
print()
print(df)

<class 'dict'>
<class 'pandas.DataFrame'>

       Nome  Idade       Cidade Estado
0   Joaquim      4     Curitiba     PR
1   Vanessa     42  Pato Branco     PR
2  Alzemiro     92     Espumoso     RS
3     Alice     33    São Paulo     SP

In [6]:
len(df) # quantidade de linhas (registros)

4

In [8]:
# criando um DataFrame a partir de um arquivo 'csv'
df = pd.read_csv('C:\Python_AgentesInteligentes\Fontes\Dados\census.csv')

print(type(df))
print()
df

<class 'pandas.DataFrame'>

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
df.columns

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='str')

In [11]:
df.head(10)

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   final-weight    32561 non-null  int64
 3   education       32561 non-null  str
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital-gain    32561 non-null  int64
 11  capital-loos    32561 non-null  int64
 12  hour-per-week   32561 non-null  int64
 13  native-country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 6.5 MB

In [13]:
df.describe()

,age,final-weight,education-num,capital-gain,capital-loos,hour-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [15]:
df.shape

(32561, 15)

In [17]:
df.isna().sum()

age               0
workclass         0
final-weight      0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loos      0
hour-per-week     0
native-country    0
income            0
dtype: int64

In [19]:
df.nunique()

age                  73
workclass             9
final-weight      21648
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
sex                   2
capital-gain        119
capital-loos         92
hour-per-week        94
native-country       42
income                2
dtype: int64

In [24]:
df['age'].unique()

array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43,
       54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
       46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
       26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
       83, 84, 85, 86, 87])

In [26]:
df[['age', 'education']]

       age    education
0       39    Bachelors
1       50    Bachelors
2       38      HS-grad
3       53         11th
4       28    Bachelors
...    ...          ...
32556   27   Assoc-acdm
32557   40      HS-grad
32558   58      HS-grad
32559   22      HS-grad
32560   52      HS-grad

[32561 rows x 2 columns]

In [27]:
# Quantidade de registros para todas as colunas
for coluna in df.columns:
    print("-------", coluna, "-------")
    print(df[coluna].value_counts())
    print()

------- age -------
age
36    898
31    888
34    886
23    877
35    876
     ...
83      6
88      3
85      3
86      1
87      1
Name: count, Length: 73, dtype: int64

------- workclass -------
workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

------- final-weight -------
final-weight
123011    13
164190    13
203488    13
148995    12
121124    12
          ..
129912     1
255835     1
34066      1
84661      1
257302     1
Name: count, Length: 21648, dtype: int64

------- education -------
education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

------- education-num -------
education-num
9     10501
10     7291
13     5355
14     1723
11     1382
7      1175
12     1067
6       933
4       646
15      576
5       514
8       433
16      413
3       333
2       168
1        51
Name: count, dtype: int64

------- marital-status -------
marital-status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

------- occupation -------
occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

------- relationship -------
relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

------- race -------
race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

------- sex -------
sex
Male      21790
Female    10771
Name: count, dtype: int64

------- capital-gain -------
capital-gain
0        29849
15024      347
7688       284
7298       246
99999      159
         ...
6097         1
1639         1
7978         1
2387         1
5060         1
Name: count, Length: 119, dtype: int64

------- capital-loos -------
capital-loos
0       31042
1902      202
1977      168
1887      159
1485       51
        ...
1944        1
2467        1
2163        1
2472        1
1411        1
Name: count, Length: 92, dtype: int64

------- hour-per-week -------
hour-per-week
40    15217
50     2819
45     1824
60     1475
35     1297
      ...
87        1
94        1
82        1
92        1
74        1
Name: count, Length: 94, dtype: int64

------- native-country -------
native-country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

------- income -------
income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [28]:
for coluna in df.columns.tolist():
    if df[coluna].dtype == 'str':
        if df[coluna].str.contains('\?').any():
            print(f"Na coluna {coluna} existem valores ?")

Na coluna workclass existem valores ?
Na coluna occupation existem valores ?
Na coluna native-country existem valores ?

In [32]:
df[df.occupation == " ?"]

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
61,32,?,293936,7th-8th,4,Married-spouse-absent,?,Not-in-family,White,Male,0,0,40,?,<=50K
69,25,?,200681,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
106,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K

In [35]:
df.sort_values(["age", 'workclass'])

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
106,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,<=50K
431,17,?,202521,11th,7,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
449,17,?,258872,11th,7,Never-married,?,Own-child,White,Female,0,0,5,United-States,<=50K
671,17,?,80077,11th,7,Never-married,?,Own-child,White,Female,0,0,20,United-States,<=50K
1325,17,?,138507,10th,6,Never-married,?,Own-child,White,Male,0,0,20,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31030,90,Private,47929,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
32277,90,Private,313749,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,25,United-States,<=50K
6232,90,Self-emp-not-inc,155981,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,10566,0,50,United-States,<=50K
10210,90,Self-emp-not-inc,282095,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
24043,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K

In [39]:
df.sort_values("age", inplace=True)
df

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
18470,17,?,86786,10th,6,Never-married,?,Own-child,White,Female,0,0,40,United-States,<=50K
18469,17,Private,104232,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,10,United-States,<=50K
32282,17,Private,311907,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K
476,17,Private,211870,9th,5,Never-married,Other-service,Not-in-family,White,Male,0,0,6,United-States,<=50K
25162,17,Private,342752,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4109,90,?,256514,Bachelors,13,Widowed,?,Other-relative,White,Female,991,0,10,United-States,<=50K
11731,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,<=50K
11512,90,Private,87285,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K
4070,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
1935,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K

In [40]:
df.to_csv("idades_em_ordem.csv")