In [9]:
import pandas as pd

# criando um DataFrame a partir de um arquivo 'csv'
df = pd.read_csv('C:\Python_AgentesInteligentes\Fontes\Dados\census.csv')

# Mostra somente os registros com idade menor do que 18
df.loc[(df["age"] < 18) & (df["workclass"] == " Private") & (df['education-num'] == 7) & (df['race'] == " Black")]

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
2801,17,Private,295488,11th,7,Never-married,Other-service,Own-child,Black,Female,0,0,25,United-States,<=50K
7755,17,Private,154398,11th,7,Never-married,Other-service,Own-child,Black,Male,0,0,16,Haiti,<=50K
10836,17,Private,126779,11th,7,Never-married,Other-service,Own-child,Black,Male,0,0,20,United-States,<=50K
14475,17,Private,222618,11th,7,Never-married,Sales,Own-child,Black,Female,0,0,30,United-States,<=50K
16994,17,Private,142457,11th,7,Never-married,Other-service,Own-child,Black,Male,0,0,20,United-States,<=50K
18593,17,Private,19752,11th,7,Never-married,Other-service,Own-child,Black,Female,0,0,25,United-States,<=50K
26088,17,Private,225507,11th,7,Never-married,Handlers-cleaners,Not-in-family,Black,Female,0,0,15,United-States,<=50K
28167,17,Private,452406,11th,7,Never-married,Sales,Own-child,Black,Female,0,0,15,United-States,<=50K
30927,17,Private,108470,11th,7,Never-married,Other-service,Own-child,Black,Male,0,0,17,United-States,<=50K

In [11]:
# Pessoas de 20 a 30 anos e divorciados (campos 'age', 'workclass', 'education-num')
df.loc[(df["age"] >= 20) & (df["age"] <= 30) & 
       (df["marital-status"] == " Divorced"), ['age', 'workclass', 'education-num']]

       age workclass  education-num
64      29   Private             10
66      28   Private             10
92      28   Private             10
158     29   Private              9
274     30   Private              9
...    ...       ...            ...
32414   29   Private              9
32471   28   Private             10
32493   24   Private              7
32516   30   Private             11
32523   30   Private              9

[477 rows x 3 columns]

In [17]:
# Pessoas com 30 anos e divorciadas
df.query("age == 18 and `marital-status` == ' Divorced'")

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
2696,18,Private,57413,Some-college,10,Divorced,Other-service,Own-child,White,Male,0,0,15,United-States,<=50K

In [22]:
# Pessoas com 18 anos e casadas
df.query("age > 18 and sex == ' Female'")

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K